### ISSUE TITLE
Nullable multidimensional arrays summary

### ISSUE THREAD

**Issue by Tamas-hi** [igloo15/MarkdownGenerator#14]
Multidimensional arrays summary works well with the previous update, but we still managed to find one unhandled type: _nullable multidimensional arrays_ --> the method they are included in  parameter don't have summary.

![Képkivágás2](https://user-images.githubusercontent.com/36476318/56351069-8be87200-61cc-11e9-9e57-a3b15074a2f0.PNG)

From the previously linked xml file, this is the relevant part:
![Képkivágás](https://user-images.githubusercontent.com/36476318/56351066-88ed8180-61cc-11e9-89d5-486d6436990a.PNG)

**Comment by igloo15** [comment]
This is a nice catch never thought of a nullable multidimension array. Will put this on my back log for today or tomorrow

**Comment by igloo15** [comment]
Nullable fix is in the latest release [v1.0.5](https://www.nuget.org/packages/igloo15.MarkdownApi.Tool/)
